language: node_js
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master

script:
  - yarn run build
  - yarn run lint
  #- yarn run stylelint
  - yarn run prettier
  - yarn test

before_deploy: yarn run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: build
  on:
    branch: master

notifications:
  email: false
